### ISSUE TITLE
Handle default with false Boolean value

### ISSUE THREAD

**Issue by sdementen** [gjeusel/ticts#2]
Seen the code in
https://github.com/gjeusel/ticts/blob/3021eb15ca6ec58aa54d6d6fe97cb761687c76e8/ticts/timeseries.py#L106, I guess a default of 0 will be considered as no default.
Probably better to test against a sentinel value (NO_DEFAULT = object()) to allow for 0 values (but also None) as default.
If default is NO_DEFAULT, an exception can be raised when required.

**Comment by gjeusel** [comment]
Indeed ! Well spotted !
And your solution is even allowing None as default, I'll implement it !

**Comment by gjeusel** [comment]
solved in #3

**Comment by gjeusel** [comment]
solved in #3
