### ISSUE TITLE
when the timeseries has only a default value, exception when operating with one value

### ISSUE THREAD

**Issue by sebastiendementen** [gjeusel/ticts#23]
This raises an IndexError on https://github.com/gjeusel/ticts/blob/00a3190d61494d8158ac24f75664d54c049dc0c3/ticts/operation.py#L56
```python
import ticts
ticts.TimeSeries(default=1.)+2
```
The row could be changed to 
`        sample_value = self.values()[0] if self.values() else self.default
`

**Comment by gjeusel** [comment]
Fixed by https://github.com/gjeusel/ticts/pull/30
