### ISSUE TITLE
add a constant to a timeseries set the default to None instead of NO_DEFAULT

### ISSUE THREAD

**Issue by sebastiendementen** [gjeusel/ticts#24]
```python
import ticts
t=ticts.TimeSeries({"2022-01-01T00:00:00":1})
print(t) # the timeseries has no default
print(t+2) # now, the timeseries has a default set to None
```
The line https://github.com/gjeusel/ticts/blob/00a3190d61494d8158ac24f75664d54c049dc0c3/ticts/operation.py#L65 should probably be changed to 
`        default = NO_DEFAULT`

**Comment by gjeusel** [comment]
Fixed by https://github.com/gjeusel/ticts/pull/27
